name: RegionMusic
version: '1.1-SNAPSHOT'
author: Lui798
main: xyz.novaserver.regionmusic.RegionMusic
api-version: 1.19
depend: [WorldGuard, NovaCore]
commands:
  rgmusic:
    permission: rgmusic.admin
    description: Admin command that reloads the plugin.
permissions:
  rgmusic.admin:
    default: op
    description: Give permission to admin command.